# Generated by Django 2.1.5 on 2019-03-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greeting',
            name='when',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
