# Generated by Django 2.1.5 on 2019-03-06 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noteable', '0002_auto_20190305_2324'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
