# Generated by Django 2.1.5 on 2019-03-29 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteable', '0005_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
