# Generated by Django 2.1.5 on 2019-03-29 19:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('noteable', '0006_auto_20190328_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
