# Generated by Django 2.1.5 on 2019-03-31 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteable', '0007_record_uploaded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABCSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('time_sig', models.CharField(default='4/4', max_length=5)),
                ('length', models.CharField(default='1/4', max_length=5)),
                ('key', models.CharField(default='Dmaj', max_length=4)),
                ('song', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
