# Generated by Django 2.1.5 on 2019-04-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteable', '0008_auto_20190330_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
