# Generated by Django 2.1.5 on 2019-04-02 21:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteable', '0009_auto_20190402_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='tempo',
            field=models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(150), django.core.validators.MinValueValidator(50)]),
        ),
    ]
