# Generated by Django 2.1.5 on 2019-04-17 14:55

from django.db import migrations, models
import noteable.validators


class Migration(migrations.Migration):

    dependencies = [
        ('noteable', '0012_sheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='recording',
            field=models.FileField(upload_to='recordings/', validators=[noteable.validators.validate_wav_extension]),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sheet',
            field=models.FileField(upload_to='sheets/', validators=[noteable.validators.validate_pdf_extension]),
        ),
    ]
